---
- hosts: ipa
  become: true
  tasks:
  - name: Installing Exam Environment Packages
    yum:
      name:
      - httpd
      - vsftpd
      - ipa-server
      - libselinux-python
      - bind*
      - ipa-server-dns
      state: present
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.5 ipa.example.com ipa
      create: yes
  - name: Adding system1 address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.6 system1.example.com system1
      create: yes
  - name: Adding system2 address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.7 system2.example.com system2
      create: yes
#  - name: Populating /etc/hosts
#    blockinfile:
#      path: /etc/hosts
#      block: |
#        {{ item.shortname}} {{ item.ip }} {{ item.name }}
#      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
#    with_items:
#    - { shortname: localhost, name: "localhost.localdomain localhost4 localhost4.localdomain4", ip: 127.0.0.1 }
#    - { shortname: localhost, name: "localhost.localdomain localhost6 localhost6.localdomain6", ip: "::1" }
#    - { shortname: ipa, name: "ipa.example.com", ip: 192.168.55.5 }
#    - { shortname: system1, name: "system1.example.com", ip: 192.168.55.6 }
#    - { shortname: system2, name: "system2.example.com", ip: 192.168.55.7 }
  - name: Configuring IPA server
    command: ipa-server-install --setup-dns --allow-zone-overlap -a 'password' --hostname=ipa.example.com -r EXAMPLE.COM -p 'password' -n example.com -U --forwarder 8.8.8.8
    ignore_errors: yes
  - name: Enabling services
    service: name={{item}} enabled=true
    with_items:
      - httpd
      - vsftpd
      - firewalld
  - name: Starting services
    service: name={{item}} state=started
    with_items:
      - vsftpd
      - firewalld
  - name: Allowing Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp