---
- hosts: ipa
  strategy: free
  gather_facts: true
  become: true
  tasks:
  - name: Setting Hostname
    command: hostnamectl set-hostname ipa.example.com
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Adding localhost IPV4 address to host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding localhost IPV6 address to host file
    lineinfile:
      path: /etc/hosts
      line: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.5 ipa.example.com ipa
      create: yes
  - name: Adding system1 address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.6 system1.example.com system1
      create: yes
  - name: Adding repo address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.4 repo.example.com repo
      create: yes
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/rpms.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    blockinfile:
      dest: /etc/yum.repos.d/rpms.repo
      block: |
       [rpms]
       name=rpms
       baseurl=http://repo/rpms
       gpgcheck=0
       enabled=1
  - name: Packages Installed.
    yum:
      name:
        - ipa-server
        - ipa-server-dns
        - chrony
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.5/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search example.com ipv4.method manual
  - name: Enabling services
    service: name={{item}} enabled=true
    with_items:
      - httpd
      - firewalld
      - chronyd
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloaded Firewall. Configuring IPA server...(Est. Time - 7 minutes)
    command: firewall-cmd --reload
  - name: Finishing IPA server Configuration
    command: ipa-server-install --setup-dns --allow-zone-overlap --auto-reverse -a 'password' --hostname=ipa.example.com -r EXAMPLE.COM -p 'password' -n example.com -U --forwarder 8.8.8.8
  - name: Adding IPA user 'dave'
    ipa_user:
        name: dave
        state: present
        krbpasswordexpiration: 20200119235959
        givenname: dave
        sn: dave
        mail:
        - dave@example.com
        telephonenumber:
        - '+555123456'
        sshpubkey:
        password: password
        uidnumber: 1001
        gidnumber: 1000
        ipa_host: ipa.example.com
        ipa_user: admin
        ipa_pass: password
    
  - name: Adding IPA user 'lisa'
    ipa_user:
        name: lisa
        state: present
        krbpasswordexpiration: 20200119235959
        givenname: lisa
        sn: lisa
        mail:
        - lisa@example.com
        telephonenumber:
        - '+555123456'
        sshpubkey:
        password: password
        uidnumber: 1002
        gidnumber: 1001
        ipa_host: ipa.example.com
        ipa_user: admin
        ipa_pass: password   
  - name: Setting SELinux To Permissive
    shell: setenforce 0
    ignore_errors: yes
  - name: Copying CA CERT
    command: cp /etc/ipa/ca.crt /var/www/html/ca.crt
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #             _         _         _          
         #           /\ \      /\ \      / /\        
         #           \ \ \    /  \ \    / /  \       
         #           /\ \_\  / /\ \ \  / / /\ \      
         #          / /\/_/ / / /\ \_\/ / /\ \ \     
         #         / / /   / / /_/ / / / /  \ \ \    
         #        / / /   / / /__\/ / / /___/ /\ \   
         #       / / /   / / /_____/ / /_____/ /\ \  
         #   ___/ / /__ / / /     / /_________/\ \ \ 
         #  /\__\/_/___/ / /     / / /_       __\ \_\
         #  \/_________\/_/      \_\___\     /____/_/
         '"#
         # Why are you here? You should be working on the system hosts...
         # Anyway, try not to reboot me or bad stuff can happen.
         #
         # You are logged into \"`hostname`\" as user \"`whoami`\"
         # This system is running `cat /etc/redhat-release`
         # kernel is `uname -r`
         "
...