---
- hosts: system
  become: true
  tasks:
  - name: Installing Exam Environment Packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - ipa-server
      - libselinux-python
      - epel-release
  - name: Installing PIP
    yum:
      name: python-pip
      state: latest
  - name: Expect much?
    shell: pip --upgrade pip ; pip install --ignore-installed pexpect
  - name: Disabling selinux
    selinux:
      state: disabled
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Adding system IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.6 system1.example.com system1
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.5 ipa.example.com ipa
      create: yes
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.6/24 ipv4.dns 192.168.55.5 ipv4.dns-search example.com ipv4.method manual
  - name: Stopping NTP services
    service: name=ntpd state=stopped
  - name: Configuring IPA client
    expect:
      command: ipa-client-install --enable-dns-updates -N --principal admin --server ipa.example.com -w password --hostname=system1.example.com --realm=EXAMPLE.COM --domain=example.com -U
      responses:
        (?i)user: "admin"
        (?i)password: "password"
  - name: Enabling services
    service: name=firewalld enabled=true
  - name: Starting services
    service: name=firewalld state=started
  - name: Rebooting machine
    reboot: