---
- hosts: system1
  strategy: free
  become: true
  gather_facts: False
  tasks:
  - name: Setting Hostname
    command: hostnamectl set-hostname system1.example.com
  - name: Fixing Resolv File
    command: echo 'nameserver 192.168.55.5' > /etc/resolv.conf
  - name: Erasing Repos
    shell: yum clean all ; rm -rf /etc/yum.repos.d/*
    ignore_errors: true
  - name: Disabling services
    selinux:
      state: permissive
      policy: targeted
    ignore_errors: yes
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.5 ipa.example.com ipa
      create: yes
  - name: Adding system IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.6 system1.example.com system1
      create: yes
  - name: Adding Repo IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.4 repo.example.com repo
      create: yes
  - name: Configuring network
    command: nmcli con mod "System enp0s8" ipv4.addresses "192.168.55.6/24 192.168.55.1" ipv4.dns 192.168.55.5 ipv4.dns-search example.com ipv4.method manual
  - name: Enabling Authconfig. Configuring IPA Client...
    command: authconfig --update --enablesssd --enablesssdauth --enablemkhomedir
  - name: IPA client Configured
    command: ipa-client-install --enable-dns-updates --force-join --mkhomedir -N --principal admin --server ipa.example.com -w password --hostname=system1.example.com --realm=EXAMPLE.COM --domain=example.com -U
    ignore_errors: yes
    async: 500
    poll: 0
    register: ipa_sleeper
  - name: Enabling services
    service: name=firewalld enabled=true
  - name: Starting services
    service: name=firewalld state=started
  - name: Finishing IPA client configuration
    async_status: jid={{ ipa_sleeper.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 40
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Welcome to the RHCSA 7 Study/Test Environment!
    debug:
      msg:
        - 'Accessing The Systems:'
        - '- IPA - 192.168.55.5'
        - '- System 1 - 192.168.55.6'
        - '- Username - vagrant'
        - '- Password - vagrant'
        - '- Access example - `ssh vagrant@192.168.55.6` or `vagrant ssh system1`'
        - ' ---------------------------------------------------------------------'
        - '- Repo is available to use from http://repo.example.com/rpms'
        - '- Happy Studying!'
        - '- System 1 is currently rebooting, it should reach login in ~20 seconds'

  - name: Building Welcome Message
    blockinfile:
      path: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '
         #          _     _        _        _         _           _          _   _        _              
         #         / /\  /\ \     /\_\     / /\      /\ \        /\ \       /\_\/\_\ _   / /\            
         #        / /  \ \ \ \   / / /    / /  \     \_\ \      /  \ \     / / / / //\_\/ /  \           
         #       / / /\ \_\ \ \_/ / /    / / /\ \__  /\__ \    / /\ \ \   /\ \/ \ \/ / /_/ /\ \          
         #      / / /\ \___\ \___/ /    / / /\ \___\/ /_ \ \  / / /\ \_\ /  \____\__/ /\_\/\ \ \         
         #      \ \ \ \/___/\ \ \_/     \ \ \ \/___/ / /\ \ \/ /_/_ \/_// /\/________/      \ \ \        
         #       \ \ \       \ \ \       \ \ \    / / /  \/_/ /____/\  / / /\/_// / /        \ \ \       
         #   _    \ \ \       \ \ \  _    \ \ \  / / /     / /\____\/ / / /    / / /          \ \ \      
         #  /_/\__/ / /        \ \ \/_/\__/ / / / / /     / / /______/ / /    / / /          __\ \ \___  
         #  \ \/___/ /          \ \_\ \/___/ / /_/ /     / / /_______\/_/    / / /          /___\_\/__/\ 
         #   \_____\/            \/_/\_____\/  \_\/      \/__________/       \/_/           \_________\/ 
         '"#
         # Welcome!
         # You are logged into \"`hostname`\" as user \"`whoami`\"
         # This system is running `cat /etc/redhat-release`
         # kernel is `uname -r`
         #
         # For root - use \`sudo\` or \`sudo su -\`
         # Repo is available to use from http://repo.example.com/rpms
         # EXAMPLE.com realm has been configured already, there are also two additional NICs
         # for troubleshooting purposes.
         # 
         # LDAP Users
         # Usernames = dave, lisa
         # Passwords = password
         "
...